# Generated by Django 4.0 on 2021-12-12 08:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=256, null=True)),
                ('sex', models.CharField(choices=[('PR', 'Pria'), ('WN', 'Wanita')], max_length=2, null=True)),
                ('pekerjaan', models.CharField(choices=[('HO', 'Honor'), ('PT', 'Pegawai Tetap'), ('DO', 'Dosen')], max_length=2, null=True)),
                ('tempat_lahir', models.CharField(max_length=256)),
                ('tanggal_lahir', models.DateField()),
                ('status', models.CharField(choices=[('LJ', 'Lajang'), ('MN', 'Menikah'), ('JD', 'Janda/Duda')], max_length=2, null=True)),
                ('alamat', models.CharField(max_length=256)),
                ('penghasilan', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Penghasilan harus lebih besar dari 0')])),
                ('tanggungan', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Tanggungan harus lebih besar dari 0')])),
                ('telpon', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('tanggal_masuk', models.DateField()),
                ('photo', models.ImageField(default='user.jpg', null=True, upload_to='static/uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=256, null=True)),
                ('sex', models.CharField(choices=[('PR', 'Pria'), ('WN', 'Wanita')], max_length=2, null=True)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Setoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nominal', models.IntegerField()),
                ('saldo', models.IntegerField()),
                ('tanggal_setor', models.DateField()),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.anggota')),
            ],
        ),
        migrations.CreateModel(
            name='Pinjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('penghasilan', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Penghasilan harus lebih besar dari 0')])),
                ('tanggungan', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Tanggungan harus lebih besar dari 0')])),
                ('nominal', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000, 'Besar Pinjaman harus lebih besar dari 100000')])),
                ('potongan_koperasi', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000, 'Potongan koperasi harus lebih besar dari 100000')])),
                ('penghasilan_end', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000, 'Penghasilan setelah potongan harus lebih besar dari 100000')])),
                ('tanggal_pinjam', models.DateField()),
                ('jatuh_tempo', models.DateField()),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.anggota')),
            ],
        ),
        migrations.CreateModel(
            name='Angsuran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nominal', models.IntegerField()),
                ('tanggal_setor', models.DateField()),
                ('pinjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pinjaman')),
            ],
        ),
    ]
