# Generated by Django 4.0 on 2022-01-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjaman',
            name='status',
            field=models.CharField(choices=[('LA', 'Lancar'), ('TL', 'Tidak Lancar')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='photo',
            field=models.ImageField(default='static/user.jpg', null=True, upload_to='static/uploads'),
        ),
    ]
